path:
  model_dir: /data/sugimoto/experiments/outputs/
  model_ner: ${path.model_dir}31882ab7d7ab4cf98087dab639884a6c
  model_relation_classifier: ${path.model_dir}b3e8f3fb8549418f9166936e47c2ffaa
  # model_change_normalizer: ${path.model_dir}31882ab7d7ab4cf98087dab639884a6c
  model_certainty_classifier: ${path.model_dir}11ab1cbff6464c97bb70ef6bd971d742
  mecab_dict: /usr/lib/mecab/seed_20200304